# This is a basic workflow that is manually triggered

name: Create Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release:
        description: 'Release Version'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        ref: gh-pages
        
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.0
      with:
        filename: ui-grid-${{ github.event.inputs.release }}.zip
        path: ./release/${{ github.event.inputs.release }}/*
        
    - name: Publish Release
      run: gh release create v${{ github.event.inputs.release }} ./ui-grid-${{ github.event.inputs.release }}.zip
      
