# This is a basic workflow that is manually triggered

name: Create Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release:
        description: 'Release Version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      RELEASE: ${{ github.event.inputs.release || github.ref_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        ref: gh-pages
        
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.0
      with:
        filename: ui-grid-${{ env.RELEASE }}.zip
        path: ./release/${{ env.RELEASE }}/*
        
    - name: Publish Release
      run: gh release create v${{ env.RELEASE }} ./ui-grid-${{ env.RELEASE }}.zip
      
